### ISSUE TITLE
docs: unexpected content

### ISSUE THREAD

**Issue by pearmini** [antvis/smart-color#10]
在 API 文章和 [color convention](https://github.com/antvis/smart-color/blob/master/docs/api/colorConvertion.md#hexToColor) 相关的部分似乎出现了不该出现的东西 🤣

![image](https://user-images.githubusercontent.com/49330279/125150607-a0c9cb00-e173-11eb-89c4-252ef5e29871.png)

**Comment by neoddish** [comment]
thx! fixed by #12
